<?php

$jobsData = array(
    'Software Architect',
    'Sales Representative',
    'Marketing',
    'Marketing Manager',
    'VP of Sales',
    'QA Manager',
    'CFO',
    'VP of Engineering',
    'VP of Marketing',
    'President and CEO',
);

$departmentsData = array(
    'Engineering',
    'Sales',
    'Marketing',
    'Accounting',
    'Corporate',
);

$employeesData = array(
    'Michael Freeman' => array(
        'dateOfBirth' => '1985-10-03',
        'department' => 'Corporate',
        'job' => 'President and CEO',
        'firstName' => 'Michael',
        'lastName' => 'Freeman',
        'email' => 'michael.freeman@fakecompany.com',
        'officePhone' => '1-522-313-4502',
        'cellPhone' => '1-462-964-1519',
        'bio' => 'Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem',
        'website' => 'http://michael-freeman.fakecompany.com',
        'twitter' => '@fake_michael_freeman',
        'profilePic' => 'Michael_Freeman.jpg',
    ),
    'Brian Quinn' => array(
        'dateOfBirth' => '1973-06-20',
        'department' => 'Marketing',
        'job' => 'VP of Marketing',
        'manager' => 'Michael Freeman',
        'firstName' => 'Brian',
        'lastName' => 'Quinn',
        'email' => 'brian.quinn@fakecompany.com',
        'officePhone' => '1-169-288-2009',
        'cellPhone' => '1-384-337-2975',
        'bio' => 'sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam.',
        'website' => 'http://brian-quinn.fakecompany.com',
        'twitter' => '@fake_brian_quinn',
        'profilePic' => 'Brian_Quinn.jpg',
    ),
    'Amy Washington' => array(
        'dateOfBirth' => '1980-02-09',
        'department' => 'Accounting',
        'job' => 'CFO',
        'manager' => 'Michael Freeman',
        'firstName' => 'Amy',
        'lastName' => 'Washington',
        'email' => 'amy.washington@fakecompany.com',
        'officePhone' => '1-315-469-0724',
        'cellPhone' => '1-203-570-1989',
        'bio' => 'enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique',
        'website' => 'http://amy-washington.fakecompany.com',
        'twitter' => '@fake_amy_washington',
        'profilePic' => 'Amy_Washington.jpg',
    ),
    'Lionel Mcknight' => array(
        'dateOfBirth' => '1972-08-06',
        'department' => 'Engineering',
        'job' => 'VP of Engineering',
        'manager' => 'Michael Freeman',
        'firstName' => 'Lionel',
        'lastName' => 'Mcknight',
        'email' => 'lionel.mcknight@fakecompany.com',
        'officePhone' => '1-303-521-9323',
        'cellPhone' => '1-142-366-7623',
        'bio' => 'id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit',
        'website' => 'http://lionel-mcknight.fakecompany.com',
        'twitter' => '@fake_lionel_mcknight',
        'profilePic' => 'Lionel_Mcknight.jpg',
    ),
    'Aaron Roman' => array(
        'dateOfBirth' => '1989-01-15',
        'department' => 'Sales',
        'job' => 'VP of Sales',
        'manager' => 'Michael Freeman',
        'firstName' => 'Aaron',
        'lastName' => 'Roman',
        'email' => 'aaron.roman@fakecompany.com',
        'officePhone' => '1-873-775-4338',
        'cellPhone' => '1-704-304-7892',
        'bio' => 'imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa',
        'website' => 'http://aaron-roman.fakecompany.com',
        'twitter' => '@fake_aaron_roman',
        'profilePic' => 'Aaron_Roman.jpg',
    ),
    'Ray Daugherty' => array(
        'dateOfBirth' => '1982-10-27',
        'department' => 'Engineering',
        'job' => 'QA Manager',
        'manager' => 'Lionel Mcknight',
        'firstName' => 'Ray',
        'lastName' => 'Daugherty',
        'email' => 'ray.daugherty@fakecompany.com',
        'officePhone' => '1-611-955-3449',
        'cellPhone' => '1-799-579-5896',
        'bio' => 'ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim',
        'website' => 'http://ray-daugherty.fakecompany.com',
        'twitter' => '@fake_ray_daugherty',
        'profilePic' => 'Ray_Daugherty.jpg',
    ),
    'Sarah Torres' => array(
        'dateOfBirth' => '1971-08-23',
        'department' => 'Engineering',
        'job' => 'Software Architect',
        'manager' => 'Lionel Mcknight',
        'firstName' => 'Sarah',
        'lastName' => 'Torres',
        'email' => 'sarah.torres@fakecompany.com',
        'officePhone' => '1-239-304-9097',
        'cellPhone' => '1-955-996-8574',
        'bio' => 'laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris',
        'website' => 'http://sarah-torres.fakecompany.com',
        'twitter' => '@fake_sarah_torres',
        'profilePic' => 'Sarah_Torres.jpg',
    ),
    'Priya Lakshman' => array(
        'dateOfBirth' => '1982-03-08',
        'department' => 'Marketing',
        'job' => 'Marketing Manager',
        'manager' => 'Brian Quinn',
        'firstName' => 'Priya',
        'lastName' => 'Lakshman',
        'email' => 'priya.lakshman@fakecompany.com',
        'officePhone' => '1-914-358-6170',
        'cellPhone' => '1-446-483-8652',
        'bio' => 'vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc',
        'website' => 'http://priya-lakshman.fakecompany.com',
        'twitter' => '@fake_priya_lakshman',
        'profilePic' => 'Priya_Lakshman.jpg',
    ),
    'Palmer Dennis' => array(
        'dateOfBirth' => '1987-02-09',
        'department' => 'Marketing',
        'job' => 'Marketing',
        'manager' => 'Brian Quinn',
        'firstName' => 'Palmer',
        'lastName' => 'Dennis',
        'email' => 'palmer.dennis@fakecompany.com',
        'officePhone' => '1-509-146-3151',
        'cellPhone' => '1-206-416-7492',
        'bio' => 'risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt,',
        'website' => 'http://palmer-dennis.fakecompany.com',
        'twitter' => '@fake_palmer_dennis',
        'profilePic' => 'Palmer_Dennis.jpg',
    ),
    'Eric Jones' => array(
        'dateOfBirth' => '1980-03-28',
        'department' => 'Sales',
        'job' => 'Sales Representative',
        'manager' => 'Aaron Roman',
        'firstName' => 'Eric',
        'lastName' => 'Jones',
        'email' => 'eric.jones@fakecompany.com',
        'officePhone' => '1-589-415-1759',
        'cellPhone' => '1-169-408-7956',
        'bio' => 'egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi',
        'website' => 'http://eric-jones.fakecompany.com',
        'twitter' => '@fake_eric_jones',
        'profilePic' => 'Eric_Jones.jpg',
    ),
    'Eve Shelton' => array(
        'dateOfBirth' => '1988-07-11',
        'department' => 'Sales',
        'job' => 'Sales Representative',
        'manager' => 'Aaron Roman',
        'firstName' => 'Eve',
        'lastName' => 'Shelton',
        'email' => 'eve.shelton@fakecompany.com',
        'officePhone' => '1-944-320-5880',
        'cellPhone' => '1-285-117-6691',
        'bio' => 'Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,',
        'website' => 'http://eve-shelton.fakecompany.com',
        'twitter' => '@fake_eve_shelton',
        'profilePic' => 'Eve_Shelton.jpg',
    ),
    'Mary Contreras' => array(
        'dateOfBirth' => '1970-05-24',
        'department' => 'Sales',
        'job' => 'Sales Representative',
        'manager' => 'Aaron Roman',
        'firstName' => 'Mary',
        'lastName' => 'Contreras',
        'email' => 'mary.contreras@fakecompany.com',
        'officePhone' => '1-278-555-9603',
        'cellPhone' => '1-611-353-1933',
        'bio' => 'sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor',
        'website' => 'http://mary-contreras.fakecompany.com',
        'twitter' => '@fake_mary_contreras',
        'profilePic' => 'Mary_Contreras.jpg',
    ),
    'Abdul Hameed' => array(
        'dateOfBirth' => '1976-12-05',
        'department' => 'Sales',
        'job' => 'Sales Representative',
        'manager' => 'Aaron Roman',
        'firstName' => 'Abdul',
        'lastName' => 'Hameed',
        'email' => 'abdul.hameed@fakecompany.com',
        'officePhone' => '1-617-117-0349',
        'cellPhone' => '1-838-196-7993',
        'bio' => 'fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida',
        'website' => 'http://abdul-hameed.fakecompany.com',
        'twitter' => '@fake_abdul_hameed',
        'profilePic' => 'Abdul_Hameed.jpg',
    ),
    'Louis Farrell' => array(
        'dateOfBirth' => '1983-02-15',
        'department' => 'Engineering',
        'job' => 'Software Architect',
        'manager' => 'Lionel Mcknight',
        'firstName' => 'Louis',
        'lastName' => 'Farrell',
        'email' => 'louis.farrell@fakecompany.com',
        'officePhone' => '1-198-934-8289',
        'cellPhone' => '1-848-491-3089',
        'bio' => 'magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum',
        'website' => 'http://louis-farrell.fakecompany.com',
        'twitter' => '@fake_louis_farrell',
        'profilePic' => 'Louis_Farrell.jpg',
    ),
    'Luke Frederick' => array(
        'dateOfBirth' => '1977-06-28',
        'department' => 'Engineering',
        'job' => 'Software Architect',
        'manager' => 'Lionel Mcknight',
        'firstName' => 'Luke',
        'lastName' => 'Frederick',
        'email' => 'luke.frederick@fakecompany.com',
        'officePhone' => '1-832-680-3072',
        'cellPhone' => '1-309-180-6944',
        'bio' => 'mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In',
        'website' => 'http://luke-frederick.fakecompany.com',
        'twitter' => '@fake_luke_frederick',
        'profilePic' => 'Luke_Frederick.jpg',
    ),
    'Branden Wright' => array(
        'dateOfBirth' => '1985-09-23',
        'department' => 'Engineering',
        'job' => 'Software Architect',
        'manager' => 'Lionel Mcknight',
        'firstName' => 'Branden',
        'lastName' => 'Wright',
        'email' => 'branden.wright@fakecompany.com',
        'officePhone' => '1-611-128-4076',
        'cellPhone' => '1-683-443-6731',
        'bio' => 'elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque',
        'website' => 'http://branden-wright.fakecompany.com',
        'twitter' => '@fake_branden_wright',
        'profilePic' => 'Branden_Wright.jpg',
    ),
);
